

services:
  backend:
    build: ./backend
    container_name: visiondock-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - visionnet

  frontend:
    build: ./frontend
    container_name: visiondock-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    networks:
      - visionnet

networks:
  visionnet:
    driver: bridge
